name: .NET Build and Test

on:
  push:
    branches:
      - main  # Replace with your branch name
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'  # Use your .NET version

    # 3. Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # 4. Build solution
    - name: Build solution
      run: dotnet build --configuration Release

    # 5. Run unit tests
    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    # 6. Publish artifacts (optional)
    - name: Publish web app
      run: dotnet publish web-app/web-app.csproj --configuration Release --output ./publish
